# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b113f3cdd9b91dfe4242d3ea8c17cafd514089ea300a794048f7cec6623f1b15e96a173b7ffa240a908cc82e2d38d25afe9ed5153cdbda64a9f454f672cef130

test:
  secret_key_base: 66033ab56dc0cb4bbf09ecc6cad120ccef229cbfa5871261ff3d48f87faead1a9ebe3b87aa1e8a5090f7b62f26dd79856f48a87a0125faaa36a5ee85a00efd84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
